# -*- coding: utf-8 -*-
"""students_performance_var_codes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXqIYkB7Mfi6tKd7nfo1IRSm7tNGl-dM
"""

import pandas as pd
import csv

archivo = '/content/StudentsPerformance_with_headers.csv'
df_performance = pd.read_csv(archivo)

with open('/content/var_codes_meanings_student_performance.csv', 'r', errors = 'ignore') as csvfile:
  lector_csv = csv.reader(csvfile)
  var_codes = list(lector_csv)

variables = df_performance.columns[1:]

mapeo = {}

for var in variables:
  mapeo[var] = {}
  for row in var_codes:
    if row[0] == var:
      mapeo[var][int(row[1])] = row[2]

for var in variables:
  df_performance[var] = df_performance[var].replace(mapeo[var])

df_performance

df_performance.to_csv('/content/updated_students_performance_dataset.csv', index=False)